// // layout.js
// "use client";

// import { Inter } from "next/font/google";
// import 'bootstrap/dist/css/bootstrap.min.css';
// import { useEffect } from "react";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Mahmoud Amr Hassan",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   useEffect(() => {
//     import('bootstrap/dist/js/bootstrap.min.js');
//   }, []);

//   return (
//     <html lang="en">
//       <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// layout.js
"use client";

import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });



export default function RootLayout({ children }) {
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap.min.js');
  }, []);

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>Mahmoud Amr Hassan</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// export const metadata = {
//   title: "Mahmoud Amr Hassan",
//   description: "Generated by create next app",
// };